### ISSUE TITLE
Examples of use

### ISSUE THREAD

**Issue by beatsm** [bruinbrown/Bleeter.CS#1]
Hi 

I am very interested in using akkadotnet for exactly this kind of thing but am having difficulty using your example. I am using postman to try and hit the controllers but have only been successful in being able to register an account.

Could you possibly show some examples of hitting the other controllers? Every time I try, I receive:

"Message": "Authorization has been denied for this request."

![image](https://cloud.githubusercontent.com/assets/3408087/6083133/586bfcbe-ae1e-11e4-903b-b7a41c838ced.png)

Thanks

**Comment by bruinbrown** [comment]
Hi,

First of all sorry about the lack of documentation, it's something that's on the todo list. To use the application, you'll need an application key. If you take a look at the AccountController, you'll see 2 endpoints to register an account and to login with an existing account. If you login or register you'll get an API key which you can then attach to requests and authenticate whoever is making the request. It uses ASP.Net identity so you can configure your backend storage provider in Startup.cs but it's currently set to use Azure table storage with an emulator connection string. Once you've got an API Key, prefix it with Bearer and put it in the Authorization header, so you'll get something like Authorization: Bearer key

**Comment by beatsm** [comment]
Thanks for the response

I have checked the AccountController and there is only the register method.

Regards

**Comment by beatsm** [comment]
Looks like an issue with my setup.

After removing all auth stuff it works a charm
